// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbopjgcyjnputwvazbes.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJib3BqZ2N5am5wdXR3dmF6YmVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNzA4NDYsImV4cCI6MjA2Njk0Njg0Nn0.lNKo5OjX0lS_8AFj74fZ-gve318IA0UL_sIYihfjR_I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});